      SUBROUTINE ALLOCATING_VARIABLES
      USE PARAM
      USE TIME
      IMPLICIT NONE
      INTEGER :: I
      TYPE(BASIN_TYPE), POINTER :: BS

      CALL WRITE_LOG('ALLOCATING MEMMORY!!!')


      DO I = 1, NBASIN

        BS => BASIN(I)
        CALL BS%BSALLOCATING

      ENDDO

      RETURN
      END SUBROUTINE ALLOCATING_VARIABLES
