      SUBROUTINE GET_BASE_FLOW(SBS, ITER)
      USE PARAM
      USE CONSTANTS
      USE TIME
      IMPLICIT NONE
      TYPE(SUBBASIN_TYPE), POINTER :: SBS
      INTEGER, INTENT(IN) :: ITER
      INTEGER :: MONTH

      IF(SBS%BASE_FLOW_TYPE.EQ.CONSTANT_DATA) THEN

        SBS%BASE_FLOW(ITER) = SBS%BF_CONST

      ELSEIF(SBS%BASE_FLOW_TYPE.EQ.MONTHLY_DATA) THEN

        MONTH = TIME_ARR(0)%getMonth()
        SBS%BASE_FLOW(ITER) = SBS%BF_MONTHLY(MONTH)

      ENDIF

      RETURN
      END SUBROUTINE GET_BASE_FLOW
