      SUBROUTINE RUN_VALIDATION_MODE
      USE TIME
      USE CALC_PARAM
      IMPLICIT NONE
      INTEGER :: I
      CHARACTER(100) :: LOGCMD


      DO
        CURRENT_IDX = CURRENT_IDX + 1
        CURRENT_TIME = CURRENT_TIME + DELTAT
        WRITE(LOGCMD,'(A8,A)')"TIME: ", TRIM(CURRENT_TIME%strftime('%d-%m-%Y %H:%M'))
        CALL WRITE_LOG(TRIM(LOGCMD))
        CALL WRITE_LOG("---===")

        CALL UPDATE_GATE_DATA


        DO I = 1,NBASIN

            CALL BASIN(I)%CALCULATING_RUNOFF

            CALL BASIN(I)%ROUTING_CALC

        ENDDO

        IF(CURRENT_TIME.EQ.END_TIME) EXIT

      ENDDO

      CALL WRITE_LOG('WRITING OUTPUT!!!')
      CALL WRITE_OUTPUT



      END SUBROUTINE RUN_VALIDATION_MODE
