      SUBROUTINE RUN_VALIDATION_MODE
      USE TIME
      USE PARAM
      IMPLICIT NONE
      INTEGER :: I

      CALL WRITE_LOG('STARTING CALCULATION!!!')

      DO
        CURRENT_IDX = CURRENT_IDX + 1
        CURRENT_TIME = CURRENT_TIME + DELTAT
        PRINT*, CURRENT_IDX

        CALL UPDATE_GATE_DATA


        DO I = 1,NBASIN
            CALL BASIN(I)%CALCULATING_RUNOFF
        ENDDO


        DO I = 1,NBASIN
            CALL BASIN(I)%ROUTING_CALC
        ENDDO

        IF(CURRENT_TIME.EQ.END_TIME) EXIT


      ENDDO




      END SUBROUTINE
