      SUBROUTINE RUN_VALIDATION_MODE
      USE TIME
      USE CALC_PARAM
      IMPLICIT NONE
      INTEGER :: I

      CALL WRITE_LOG('STARTING CALCULATION!!!')

      DO
        CURRENT_IDX = CURRENT_IDX + 1
        CURRENT_TIME = CURRENT_TIME + DELTAT
        PRINT*, CURRENT_IDX

        CALL UPDATE_GATE_DATA


        DO I = 1,NBASIN
          
            CALL BASIN(I)%CALCULATING_RUNOFF

            CALL BASIN(I)%ROUTING_CALC

        ENDDO

        IF(CURRENT_TIME.EQ.END_TIME) EXIT

      ENDDO

      CALL WRITE_OUTPUT 



      END SUBROUTINE RUN_VALIDATION_MODE
