      SUBROUTINE FORECASTING
      USE TIME
      USE CALC_PARAM
      USE COMMON_PARAM
      INTEGER :: CURRENT_IDX_SAVE
      TYPE(DATETIME) :: CURRENT_TIME_SAVE

      CURRENT_IDX_SAVE = CURRENT_IDX
      CURRENT_TIME_SAVE = CURRENT_TIME

      TIME_LOOP:DO

        CURRENT_IDX = CURRENT_IDX + 1
        CURRENT_TIME = CURRENT_TIME + DELTAT

        CALL UPDATE_GATE_DATA


        DO I = 1,NBASIN

            CALL BASIN(I)%CALCULATING_RUNOFF

            CALL BASIN(I)%ROUTING_CALC

        ENDDO

        IF(CURRENT_IDX.EQ.CURRENT_IDX_SAVE + NFCT) THEN

            CURRENT_IDX = CURRENT_IDX_SAVE
            CURRENT_TIME = CURRENT_TIME_SAVE
            EXIT TIME_LOOP

        ENDIF


      ENDDO TIME_LOOP


      END SUBROUTINE FORECASTING
