      SUBROUTINE GET_REACH_INFLOW(BS, RCH, ITER)
      USE PARAM
      USE CONSTANTS
      USE TIME
      IMPLICIT NONE
      TYPE(REACH_TYPE), POINTER :: RCH
      TYPE(BASIN_TYPE), POINTER :: BS
      TYPE(SUBBASIN_TYPE), POINTER :: SBS
      TYPE(SOURCE_TYPE), POINTER :: SRC
      TYPE(RESERVOIR_TYPE), POINTER :: RES
      INTEGER, INTENT(IN) :: ITER
      INTEGER :: I, J

      RCH%INFLOW(ITER) = 0.0D0

      DO I = 1, BS%NSUBBASIN

        SBS => BS%SUBBASIN(I)
        IF(TRIM(SBS%DOWNSTREAM).EQ.TRIM(RCH%NAME)) THEN

            RCH%INFLOW(ITER) = RCH%INFLOW(ITER) + SBS%TOTAL_FLOW(ITER)

        ENDIF

      ENDDO

      DO I = 1, BS%NSOURCE

        SRC => BS%SOURCE(I)
        IF(TRIM(SRC%DOWNSTREAM).EQ.TRIM(RCH%NAME)) THEN

            RCH%INFLOW(ITER) = RCH%INFLOW(ITER) + SRC%SRC_DATA%GATE_DATA(ITER)

        ENDIF

      ENDDO

      DO I = 1, BS%NRESERVOIR

        RES => BS%RESERVOIR(I)
        IF(TRIM(RES%DOWNSTREAM).EQ.TRIM(RCH%NAME)) THEN

            RCH%INFLOW(ITER) = RCH%INFLOW(ITER) + RES%OUTFLOW(ITER)

        ENDIF

      ENDDO

      RETURN
      END SUBROUTINE GET_REACH_INFLOW

