      SUBROUTINE RESET_MEMORIES
      USE CALC_PARAM
      IMPLICIT NONE
      INTEGER :: I

      DO I = 1, NBASIN

        CALL BASIN(I)%BSRESET_MEMORIES

      ENDDO

      CURRENT_IDX = NFCT*2

      RETURN
      END SUBROUTINE RESET_MEMORIES
