      SUBROUTINE CALCULATING_RUNOFF(SEFT)
      IMPLICIT NONE
      CLASS(BASIN_TYPE), INTENT(INOUT) :: SEFT
      TYPE(SUBBASIN_TYPE), POINTER :: SBS
      INTEGER :: J


      DO J = 1,SEFT%NSUBBASIN

        SBS => SEFT%SUBBASIN(J)
        CALL SBS%AVERAGED_PRECIP
        IF(SBS%LOSSRATE.NE.0) THEN

            CALL SBS%LOSS_CALC

        ELSE

            IF(SBS%NPRECIP_GATE.GT.0) THEN

                SBS%EXCESS(CURRENT_IDX) = SBS%AVGPRECIP(CURRENT_IDX)

            ENDIF

        ENDIF

        IF(SBS%BASE_FLOW_TYPE.NE.0) SBS%BASE_FLOW(CURRENT_IDX) = SBS%GET_BASE_FLOW(TIME_ARR(CURRENT_IDX))
        IF(SBS%TRANSFORM.NE.0)CALL SBS%TRANSFORM_CALC
        SBS%TOTAL_FLOW(CURRENT_IDX) = SBS%DIRECT_FLOW(CURRENT_IDX) + SBS%BASE_FLOW(CURRENT_IDX)

      ENDDO

      RETURN
      END SUBROUTINE CALCULATING_RUNOFF
