      SUBROUTINE UPDATE_GATE_DATA
      USE PARAM
      IMPLICIT NONE
      INTEGER :: I, J, IERR
      TYPE(BASIN_TYPE), POINTER :: BS

      DO I = 1, NBASIN

        BS => BASIN(I)
        DO J = 1, BS%NGATE
            IERR = BS%GATE(J)%SET_CURRENT_DATA(SIMULATION_MODE)
            IF(IERR.EQ.1) CALL WRITE_ERRORS(' GET GATE DATA FALSE!!!')
        ENDDO

      ENDDO

      END SUBROUTINE UPDATE_GATE_DATA
