      SUBROUTINE UPDATE_GATE_DATA
      USE COMMON_PARAM
      USE CALC_PARAM
      USE CONSTANTS
      IMPLICIT NONE
      INTEGER :: I, J, IERR,CNT
      TYPE(BASIN_TYPE), POINTER :: BS


      DO I = 1, NBASIN

        BS => BASIN(I)
        DO J = 1, BS%NGATE
            IF(BS%GATE(J)%GATETYPE.NE.TURBIN__DISCHARGE_GATE.AND.
     &         SIMULATION_MODE.EQ.REAL_TIME_MODE.AND.
     &         ACTIVE_MODE.EQ.PREDICT_CALC_MODE)CYCLE
            CNT = 0
            SLEEPLOOP: DO
                IERR = BS%GATE(J)%SET_CURRENT_DATA()
                IF(IERR.EQ.0) EXIT SLEEPLOOP
                IF(SIMULATION_MODE.EQ.VALIDATION_MODE) CALL WRITE_ERRORS("CAN NOT FIND TARGET GATE DATA!")
                CNT = CNT + 1
                IF(CNT.GT.10) CALL WRITE_ERRORS("GET DATA FALSED!")
                CALL SLEEP(15)
            ENDDO SLEEPLOOP
        ENDDO

      ENDDO

      END SUBROUTINE UPDATE_GATE_DATA
